import Head from "next/head";
import Image from "next/image";
import localFont from "next/font/local";
import styles from "@/styles/Home.module.css";
import Counter from "@/pages/Counter";
import Github from "@/pages/Github";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export default function Home() {
  return (
    <>
      <Head>
        <title>NextJs Assignment</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
      >
        <main className={styles.main}>
            <h1>Burgin Luker NextJs Assignment</h1>
            <div style={{display: "flex", margin: "20px", textAlign: "center"}}>
                <div style={{ margin: "20px"}}>
                    <Counter color={"green"} increment={1}/>
                </div>
                <div style={{ margin: "20px"}}>
                    <Counter color={"red"} increment={2}/>
                </div>
            </div>
            <Github />
        </main>
      </div>
    </>
  );
}
